### ISSUE TITLE
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by giovannipiller** [csscomb/core#11]
When installing this package via NPM, I get the following warning:

> npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by tonyganch** [comment]
@giovannipiller, can you please send a PR?

**Comment by marcovtwout** [comment]
@tonyganch This issue is fixed in the dev branch but appearantly not released yet. Could you do a new release?

```
$ npm install csscomb-core --save-dev
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by redbonzai** [comment]
Run the command : `npm install -g minimatch@3.0.2`
The result should be : `+ minimatch@3.0.2
added 4 packages in 2.186s`

Then run : `npm install`
Problem fixed.  Yay!

**Comment by Mukesh-Lekhrajani** [comment]
J:\JavaScript\AngularJS\angular-reddit>npm install -g minimatch
+ minimatch@3.0.4
updated 1 package in 3.099s

J:\JavaScript\AngularJS\angular-reddit>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 43877 packages in 37.542s

10 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

J:\JavaScript\AngularJS\angular-reddit>
